chore(deps-dev): Bump jsii from 1.62.0 to 1.69.0 (#403)
Bumps [jsii](https://github.com/aws/jsii/tree/HEAD/packages/jsii) from 1.62.0 to 1.69.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/aws/jsii/releases">jsii's releases</a>.</em></p>
<blockquote>
<h2>v1.69.0</h2>
<h3>Features</h3>
<ul>
<li><strong>dotnet:</strong> distinguish error types (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3764">#3764</a>) (<a href="https://github.com/aws/jsii/commit/283dae57647cb28323f4f02ef040deef81248f3a">283dae5</a>)</li>
</ul>
<h3>Bug Fixes</h3>
<ul>
<li><strong>jsii:</strong> missing deprecation warning in collections (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3756">#3756</a>) (<a href="https://github.com/aws/jsii/commit/72f2e7ca82555c2dce647f873bed923a98808f95">72f2e7c</a>), closes <a href="https://github-redirect.dependabot.com/aws/jsii/issues/3755">#3755</a></li>
<li><strong>kernel:</strong> EPERM on rename operation on Windows (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3769">#3769</a>) (<a href="https://github.com/aws/jsii/commit/bab1d388e8bed41c4930566ba5834acf57cc696c">bab1d38</a>), closes <a href="https://github-redirect.dependabot.com/aws/jsii/issues/992">#992</a> <a href="https://github-redirect.dependabot.com/aws/jsii/issues/3724">#3724</a> <a href="https://github-redirect.dependabot.com/aws/jsii/issues/3751">#3751</a></li>
<li><strong>python:</strong> bin script python support, test argument passing (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3762">#3762</a>) (<a href="https://github.com/aws/jsii/commit/0cf500864c918a799505625b08025293431031c7">0cf5008</a>), closes <a href="https://github-redirect.dependabot.com/aws/jsii/issues/3694">#3694</a></li>
</ul>
<h2>v1.68.0</h2>
<h3>Features</h3>
<ul>
<li><strong>kernel:</strong> distinguish framework errors from userland errors in Java (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3747">#3747</a>) (<a href="https://github.com/aws/jsii/commit/a4d39c6fb619cd4d7c9103ec70a731ab6fb23374">a4d39c6</a>)</li>
</ul>
<h3>Bug Fixes</h3>
<ul>
<li><strong>jsii:</strong> unable to return Promise (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3752">#3752</a>) (<a href="https://github.com/aws/jsii/commit/852b3dc5da113546bc090d99f9250104f526f5af">852b3dc</a>), closes <a href="https://github-redirect.dependabot.com/aws/jsii/issues/51">#51</a></li>
<li><strong>pacmak:</strong> .NET bindings fail to compile with error CS8120 (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3760">#3760</a>) (<a href="https://github.com/aws/jsii/commit/783ec7f1d40619677f34318ee247244b682cd92d">783ec7f</a>), closes <a href="https://github-redirect.dependabot.com/aws/jsii/issues/3759">#3759</a></li>
<li><strong>runtime:</strong> type not found (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3763">#3763</a>) (<a href="https://github.com/aws/jsii/commit/c7dfad3ec905a5ee795be1d313d9c078ab3b4234">c7dfad3</a>), closes <a href="https://github-redirect.dependabot.com/aws/jsii/issues/3742">#3742</a></li>
</ul>
<h2>v1.67.0</h2>
<h3>Features</h3>
<ul>
<li><strong>java:</strong> dynamic type checking for union-typed parameters (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3703">#3703</a>) (<a href="https://github.com/aws/jsii/commit/26ca47cfef15ce346f610d75991e62d5bd0597e3">26ca47c</a>)</li>
<li><strong>java:</strong> utility to perform unsafe cast (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3730">#3730</a>) (<a href="https://github.com/aws/jsii/commit/4a52d4cbc31e88d744ed84d5a64df8c8f9651017">4a52d4c</a>)</li>
<li><strong>kernel:</strong> experimental runtime package cache (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3724">#3724</a>) (<a href="https://github.com/aws/jsii/commit/4c2dcd5562b2abdfb2a454cb0ee487c4a0533e12">4c2dcd5</a>), closes <a href="https://github-redirect.dependabot.com/aws/jsii/issues/3389">#3389</a></li>
</ul>
<h3>Bug Fixes</h3>
<ul>
<li><strong>java:</strong> type generation code-gen issues (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3735">#3735</a>) (<a href="https://github.com/aws/jsii/commit/cf04f79d28d10861a7e3e7d80b7dfb5dabd0068b">cf04f79</a>)</li>
<li><strong>pacmak:</strong> crash when generating java code (<a href="https://github.com/aws/jsii/commit/1fd58db1e94a0024d173d53597416f1d2a2fa941">1fd58db</a>)</li>
</ul>
<h2>v1.66.0</h2>
<h3>Features</h3>
<ul>
<li><strong>go:</strong> emit deprecation warning when using go1.16 and go1.17 (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3718">#3718</a>) (<a href="https://github.com/aws/jsii/commit/3cf5c28b26e189db1a05f9543a5f6f38583e8868">3cf5c28</a>)</li>
<li><strong>go:</strong> runtime type check type unions (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3712">#3712</a>) (<a href="https://github.com/aws/jsii/commit/c73c2ee6d973ea8ff14b320a5f97ae017107ebab">c73c2ee</a>)</li>
</ul>
<h3>Bug Fixes</h3>
<ul>
<li><strong>.net:</strong> missing dynamic type checking for collection-nested unions (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3720">#3720</a>) (<a href="https://github.com/aws/jsii/commit/362326e989e1d9f2a032d4c15c34f3d60e712051">362326e</a>)</li>
<li><strong>rosetta:</strong> rosetta reader expects default tablet file to be uncompressed (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3723">#3723</a>) (<a href="https://github.com/aws/jsii/commit/9768e2a7f2eb8847d8d06e3f40deeedac0c7dec4">9768e2a</a>)</li>
<li>type unions in variadic position leads to invalid code-gen (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3722">#3722</a>) (<a href="https://github.com/aws/jsii/commit/93aec85ada9fd9e505591766b8e87ee53c0bde6b">93aec85</a>)</li>
</ul>

</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/aws/jsii/blob/main/CHANGELOG.md">jsii's changelog</a>.</em></p>
<blockquote>
<h2><a href="https://github.com/aws/jsii/compare/v1.68.0...v1.69.0">1.69.0</a> (2022-09-27)</h2>
<h3>Features</h3>
<ul>
<li><strong>dotnet:</strong> distinguish error types (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3764">#3764</a>) (<a href="https://github.com/aws/jsii/commit/283dae57647cb28323f4f02ef040deef81248f3a">283dae5</a>)</li>
</ul>
<h3>Bug Fixes</h3>
<ul>
<li><strong>jsii:</strong> missing deprecation warning in collections (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3756">#3756</a>) (<a href="https://github.com/aws/jsii/commit/72f2e7ca82555c2dce647f873bed923a98808f95">72f2e7c</a>), closes <a href="https://github-redirect.dependabot.com/aws/jsii/issues/3755">#3755</a></li>
<li><strong>kernel:</strong> EPERM on rename operation on Windows (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3769">#3769</a>) (<a href="https://github.com/aws/jsii/commit/bab1d388e8bed41c4930566ba5834acf57cc696c">bab1d38</a>), closes <a href="https://github-redirect.dependabot.com/aws/jsii/issues/992">#992</a> <a href="https://github-redirect.dependabot.com/aws/jsii/issues/3724">#3724</a> <a href="https://github-redirect.dependabot.com/aws/jsii/issues/3751">#3751</a></li>
<li><strong>python:</strong> bin script python support, test argument passing (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3762">#3762</a>) (<a href="https://github.com/aws/jsii/commit/0cf500864c918a799505625b08025293431031c7">0cf5008</a>), closes <a href="https://github-redirect.dependabot.com/aws/jsii/issues/3694">#3694</a></li>
</ul>
<h2><a href="https://github.com/aws/jsii/compare/v1.67.0...v1.68.0">1.68.0</a> (2022-09-22)</h2>
<h3>Features</h3>
<ul>
<li><strong>kernel:</strong> distinguish framework errors from userland errors in Java (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3747">#3747</a>) (<a href="https://github.com/aws/jsii/commit/a4d39c6fb619cd4d7c9103ec70a731ab6fb23374">a4d39c6</a>)</li>
</ul>
<h3>Bug Fixes</h3>
<ul>
<li><strong>jsii:</strong> unable to return Promise (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3752">#3752</a>) (<a href="https://github.com/aws/jsii/commit/852b3dc5da113546bc090d99f9250104f526f5af">852b3dc</a>), closes <a href="https://github-redirect.dependabot.com/aws/jsii/issues/51">#51</a></li>
<li><strong>pacmak:</strong> .NET bindings fail to compile with error CS8120 (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3760">#3760</a>) (<a href="https://github.com/aws/jsii/commit/783ec7f1d40619677f34318ee247244b682cd92d">783ec7f</a>), closes <a href="https://github-redirect.dependabot.com/aws/jsii/issues/3759">#3759</a></li>
<li><strong>runtime:</strong> type not found (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3763">#3763</a>) (<a href="https://github.com/aws/jsii/commit/c7dfad3ec905a5ee795be1d313d9c078ab3b4234">c7dfad3</a>), closes <a href="https://github-redirect.dependabot.com/aws/jsii/issues/3742">#3742</a></li>
</ul>
<h2><a href="https://github.com/aws/jsii/compare/v1.66.0...v1.67.0">1.67.0</a> (2022-09-02)</h2>
<h3>Features</h3>
<ul>
<li><strong>java:</strong> dynamic type checking for union-typed parameters (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3703">#3703</a>) (<a href="https://github.com/aws/jsii/commit/26ca47cfef15ce346f610d75991e62d5bd0597e3">26ca47c</a>)</li>
<li><strong>java:</strong> utility to perform unsafe cast (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3730">#3730</a>) (<a href="https://github.com/aws/jsii/commit/4a52d4cbc31e88d744ed84d5a64df8c8f9651017">4a52d4c</a>)</li>
<li><strong>kernel:</strong> experimental runtime package cache (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3724">#3724</a>) (<a href="https://github.com/aws/jsii/commit/4c2dcd5562b2abdfb2a454cb0ee487c4a0533e12">4c2dcd5</a>), closes <a href="https://github-redirect.dependabot.com/aws/jsii/issues/3389">#3389</a></li>
</ul>
<h3>Bug Fixes</h3>
<ul>
<li><strong>java:</strong> type generation code-gen issues (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3735">#3735</a>) (<a href="https://github.com/aws/jsii/commit/cf04f79d28d10861a7e3e7d80b7dfb5dabd0068b">cf04f79</a>)</li>
<li><strong>pacmak:</strong> crash when generating java code (<a href="https://github.com/aws/jsii/commit/1fd58db1e94a0024d173d53597416f1d2a2fa941">1fd58db</a>)</li>
</ul>
<h2><a href="https://github.com/aws/jsii/compare/v1.65.1...v1.66.0">1.66.0</a> (2022-08-29)</h2>
<h3>Features</h3>
<ul>
<li><strong>go:</strong> emit deprecation warning when using go1.16 and go1.17 (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3718">#3718</a>) (<a href="https://github.com/aws/jsii/commit/3cf5c28b26e189db1a05f9543a5f6f38583e8868">3cf5c28</a>)</li>
<li><strong>go:</strong> runtime type check type unions (<a href="https://github-redirect.dependabot.com/aws/jsii/issues/3712">#3712</a>) (<a href="https://github.com/aws/jsii/commit/c73c2ee6d973ea8ff14b320a5f97ae017107ebab">c73c2ee</a>)</li>
</ul>

</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/aws/jsii/commit/bcce9897a2f0da20c3af6b3573ae08d5cd8398df"><code>bcce989</code></a> chore(jsii): enable skipLibCheck (<a href="https://github.com/aws/jsii/tree/HEAD/packages/jsii/issues/3754">#3754</a>)</li>
<li><a href="https://github.com/aws/jsii/commit/72f2e7ca82555c2dce647f873bed923a98808f95"><code>72f2e7c</code></a> fix(jsii): missing deprecation warning in collections (<a href="https://github.com/aws/jsii/tree/HEAD/packages/jsii/issues/3756">#3756</a>)</li>
<li><a href="https://github.com/aws/jsii/commit/c7dfad3ec905a5ee795be1d313d9c078ab3b4234"><code>c7dfad3</code></a> fix(runtime): type not found (<a href="https://github.com/aws/jsii/tree/HEAD/packages/jsii/issues/3763">#3763</a>)</li>
<li><a href="https://github.com/aws/jsii/commit/3d2126cea542f1adbb0e3cae18b8f4f0bfd6b8b0"><code>3d2126c</code></a> chore: npm-check-updates &amp;&amp; yarn upgrade (<a href="https://github.com/aws/jsii/tree/HEAD/packages/jsii/issues/3736">#3736</a>)</li>
<li><a href="https://github.com/aws/jsii/commit/852b3dc5da113546bc090d99f9250104f526f5af"><code>852b3dc</code></a> fix(jsii): unable to return Promise&lt;void&gt; (<a href="https://github.com/aws/jsii/tree/HEAD/packages/jsii/issues/3752">#3752</a>)</li>
<li><a href="https://github.com/aws/jsii/commit/0cc5b1179d1f738b8cbbcb0cb3ff5b118c1c8429"><code>0cc5b11</code></a> chore: npm-check-updates &amp;&amp; yarn upgrade (<a href="https://github.com/aws/jsii/tree/HEAD/packages/jsii/issues/3711">#3711</a>)</li>
<li><a href="https://github.com/aws/jsii/commit/69559a585fa13f79856d6c954a909a1f6d175e64"><code>69559a5</code></a> chore: npm-check-updates &amp;&amp; yarn upgrade (<a href="https://github.com/aws/jsii/tree/HEAD/packages/jsii/issues/3682">#3682</a>)</li>
<li><a href="https://github.com/aws/jsii/commit/7eb11b7d3173f450cd6bd4c29180f6edf7f6b219"><code>7eb11b7</code></a> feat(jsii): allow specifying baseUrl and paths in tsconfig.json (<a href="https://github.com/aws/jsii/tree/HEAD/packages/jsii/issues/3662">#3662</a>)</li>
<li><a href="https://github.com/aws/jsii/commit/f1ac3937f94c54a0339fd6ea3963cd7f42626e29"><code>f1ac393</code></a> chore: npm-check-updates &amp;&amp; yarn upgrade (<a href="https://github.com/aws/jsii/tree/HEAD/packages/jsii/issues/3661">#3661</a>)</li>
<li>See full diff in <a href="https://github.com/aws/jsii/commits/v1.69.0/packages/jsii">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=jsii&package-manager=npm_and_yarn&previous-version=1.62.0&new-version=1.69.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)


</details>